import type { Metadata } from "next";

import "./globals.css";
import { Header } from "./components/Sections/Header";
import { Footer } from "./components/Sections/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="antialiased bg-background text-foreground"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
